# Generated by Django 3.1.7 on 2021-04-13 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capp', '0003_auto_20210413_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.CharField(default='post1', max_length=100),
            preserve_default=False,
        ),
    ]
