# Generated by Django 3.1.7 on 2021-04-13 18:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('capp', '0004_post_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='img',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='assets/images'),
            preserve_default=False,
        ),
    ]
